server:
  port: 9090

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://localhost:3306/bookings?createDatabaseIfNotExist=true
    username: root
    password: asnpa 94
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create